### ISSUE TITLE
Videography Featured Films – Can we autoplay the featured films + hide controls + controls appear on hover?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#16]
<img width="1103" alt="Screenshot 2023-06-22 at 6 52 31 pm" src="https://github.com/markendley/pprjne/assets/137390062/579fbfc2-6fc8-4180-9ed3-1d43cdc3104f">

**Comment by markendley** [comment]
sorry, this is tough one

Actually the autoplay is already turned on. But the browsers just won't autoplay it.

**Comment by jillian-sun** [comment]
let's leave as is, thanks mark.
