### ISSUE TITLE
Videography Featured Films – when you click on the arrows, the order is wrong. e.g. when it says ‘Danielle & Peter’ are up next, it is not their video that plays next

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#17]
<img width="358" alt="Screenshot 2023-06-22 at 6 53 28 pm" src="https://github.com/markendley/pprjne/assets/137390062/3a202f7e-e6b0-45a6-84c9-c8de731cb9c8">

**Comment by markendley** [comment]
fixed
