### ISSUE TITLE
Photo Booth Backdrop Selection – preview of images on either side has disappeared after uploading a batch of my own images

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#25]
<img width="1498" alt="Screenshot 2023-06-22 at 7 01 28 pm" src="https://github.com/markendley/pprjne/assets/137390062/fa6d2e9d-1a3f-46ff-bb23-d78a8efd2111">

<img width="770" alt="Screenshot 2023-06-22 at 7 01 51 pm" src="https://github.com/markendley/pprjne/assets/137390062/45358406-93d1-4ba6-8278-8f88040db203">

**Comment by markendley** [comment]
fixed
