### ISSUE TITLE
Cookies acceptance – can we change it to the brand Sage colour + change from bold to regular font weight? 

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#27]
<img width="1325" alt="Screenshot 2023-06-22 at 7 07 34 pm" src="https://github.com/markendley/pprjne/assets/137390062/53deba42-8e93-4115-858a-3754aaa7dc61">

**Comment by markendley** [comment]
done

**Comment by jillian-sun** [comment]
thank you! where can i edit the cookies message? client may want to change working and remove link. thanks

**Comment by markendley** [comment]
I just created a new field on the Site Wide page

http://demoplatform.net/pepperjune/wp-admin/admin.php?page=site-wide
