### ISSUE TITLE
Homepage Mobile – Some menu items are hidden by logo 

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#29]
![IMG_239C51CC2D79-1](https://github.com/markendley/pprjne/assets/137390062/0ea32b1b-9f47-4dae-add7-0894fc67d1bd)

**Comment by markendley** [comment]
sorry I can't replicate it

I'll need you to send me a link

Have you used this before?
https://www.whatsmybrowser.org/

**Comment by jillian-sun** [comment]
As in, on mobile, when i press on menu icon, the logo hides some of the menu items. Also the big logo shows when it should be the leaf icon. can we ensure it is the leaf icon and that all menu items are shown below the logo? thanks! 
![IMG_BB11C7F1908F-1](https://github.com/markendley/pprjne/assets/137390062/84a0d9a2-c7fa-490c-b01f-466dac9ac801)

**Comment by markendley** [comment]
oh

ok fixed

**Comment by jillian-sun** [comment]
icon is fixed, but when i'm at the top of the page, it still cuts off the menu items, please see: 

![IMG_1F59B67AB961-1](https://github.com/markendley/pprjne/assets/137390062/1d5be738-284e-4f26-8153-6f64617a96f9)

**Comment by markendley** [comment]
OK try now!

**Comment by jillian-sun** [comment]
sorry mark! now it cuts off after the nav bar 

![IMG_86D20EF8BBA8-1](https://github.com/markendley/pprjne/assets/137390062/9847a20e-a7ce-4698-a568-a517e49d8a82)

**Comment by markendley** [comment]
fixed
