### ISSUE TITLE
Audio Guest Book – Curve doesn’t overlay on image fully - crops weirdly (same on mobile)

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#31]
<img width="1512" alt="Screenshot 2023-06-22 at 7 42 35 pm" src="https://github.com/markendley/pprjne/assets/137390062/f82b658c-8163-4a34-b33a-13599bbbb44d">

**Comment by markendley** [comment]
fixed

**Comment by jillian-sun** [comment]
cleared my cache but still there 
<img width="1568" alt="Screenshot 2023-07-05 at 5 11 11 pm" src="https://github.com/markendley/pprjne/assets/137390062/2bdf1026-256b-4898-8eab-a12fe14a72a8">

**Comment by markendley** [comment]
I might need to add a bit more margin of error. How does that work for you now?
