### ISSUE TITLE
Audio Guest Book – How it works  text on left should be fixed and images to scroll behind, text should not scroll with images

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#32]
<img width="927" alt="Screenshot 2023-06-22 at 7 43 40 pm" src="https://github.com/markendley/pprjne/assets/137390062/811e71c7-e6d8-4a0f-9006-4788421d7b5a">

**Comment by markendley** [comment]
done

**Comment by jillian-sun** [comment]
images are not behind text and images are too cropped in:

<img width="1907" alt="Screenshot 2023-07-07 at 3 59 55 pm" src="https://github.com/markendley/pprjne/assets/137390062/21c7be80-a1cd-4040-93a2-9a9b65b2424e">

**Comment by markendley** [comment]
see #33 about the images.

**Comment by markendley** [comment]
The images are behind the text.

So this is not what you wanted?

<img width="959" alt="Screenshot 2023-07-07 at 4 19 23 pm" src="https://github.com/markendley/pprjne/assets/6570606/52bbdfae-a2d7-4d3f-8ad6-cafcf8031d8b">

**Comment by jillian-sun** [comment]
yes, this is good, but can we add a background to the text so it looks like it scrolls behind a box? 
<img width="719" alt="Screenshot 2023-07-07 at 4 30 18 pm" src="https://github.com/markendley/pprjne/assets/137390062/bfae7f62-454d-4b96-a0e9-6dd6d457e3b8">

**Comment by markendley** [comment]
done
