### ISSUE TITLE
Audio Guest Book - How it works section - Can image ratios be fixed to how it is in Figma file? please make sure images are not stretched/distorted as well

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#33]
<img width="864" alt="Screenshot 2023-06-22 at 7 45 20 pm" src="https://github.com/markendley/pprjne/assets/137390062/8ac2b45a-b1a1-43c9-b1b3-752df5bb1da4">

**Comment by markendley** [comment]
Oh @jillian-sun ,

I can create the image containers to match the same ratios as the figma (I just did), but the you gotta upload images that can fit inside them.

Right now you've uploaded square gifs, but in order to make them fit in portait containers I have no choice but to scale them up.

**Comment by jillian-sun** [comment]
ahhh okay gotcha. sorry to be annoying then, can we please revert this section to what we had before then?

**Comment by markendley** [comment]
done
