### ISSUE TITLE
Pepper June Car – Curve doesn’t overlay on image fully - crops weirdly (same on mobile)

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#35]
<img width="1512" alt="Screenshot 2023-06-22 at 7 49 52 pm" src="https://github.com/markendley/pprjne/assets/137390062/b2d14025-f98a-4aba-b005-e7dd0b53f415">

**Comment by markendley** [comment]
fixed

**Comment by jillian-sun** [comment]
Cleared my cache but it's still there 
<img width="1559" alt="Screenshot 2023-07-05 at 5 03 06 pm" src="https://github.com/markendley/pprjne/assets/137390062/e0357a63-52e6-4ea0-9914-4a67475d70e7">

**Comment by markendley** [comment]
ok try now
