### ISSUE TITLE
Dropdown menu – when you hover away from menu item, design doesn’t return to default state (100% opacity + no image)

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#4]
<img width="1509" alt="Screenshot 2023-06-22 at 6 37 24 pm" src="https://github.com/markendley/pprjne/assets/137390062/93ded475-bd0c-4a18-8ad1-ac14a0203f80">

**Comment by markendley** [comment]
fixed

**Comment by jillian-sun** [comment]
when i hover away, the menu items should go back to 100%m, currently they're still at low opacity when i hover away.
<img width="781" alt="Screenshot 2023-07-07 at 12 05 06 pm" src="https://github.com/markendley/pprjne/assets/137390062/f81a1f60-735b-4ae7-bfe6-e575eeeaef41">

**Comment by markendley** [comment]
this is getting tricky, but I think I nailed it...
what do you think?

**Comment by jillian-sun** [comment]
perfection!! thank you
