### ISSUE TITLE
Pricing Collection Calculator – Whitelisting issue? (see comment)

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#41]
Client says: The embed code for this is likely not working as we need to whitelist the site in order for it to properly function, just FYI!  

Not sure what they mean here, do you have any ideas?

**Comment by markendley** [comment]
I know what whitelisting is, but I'm not sure if it's the issue.

... Maybe I need to provide somebody the IP address of my testing server and once that is "whitelisted", I can make the embed code work.

My Site IP is 35.213.242.248

**Comment by jillian-sun** [comment]
they've provided the code:

<div class="calconic-calculator"  data-calculatorid="615d1bfa9efd5f002c455361"></div>
<script>
  (function() { var qs,j,q,s,d=document, gi=d.getElementById,
  ce=d.createElement, gt=d.getElementsByTagName,
  id="calconic_", b="https://cdn.calconic.com/static/js/";
  if(!gi.call(d,id)) { j=ce.call(d,"script"); [j.id](http://j.id/)=id; j.type="text/javascript"; j.async=true;
  j.dataset.calconic=true;
  j.src=b+"calconic.min.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(j,q) }
})();
</script>

**Comment by markendley** [comment]
There's a broken tag somewhere, can you try again?

(or send me a txt file?)

**Comment by jillian-sun** [comment]
Hey mark, spoke to the client and he's happy to work with what you've built instead. can we please make sure all field options are correct as per the current one on their current site and that the calculator is active and working?

**Comment by markendley** [comment]
OK cool,
but I need the algorithm.


<img width="766" alt="Screenshot 2023-07-07 at 1 21 22 pm" src="https://github.com/markendley/pprjne/assets/6570606/0cd0dc56-ac56-44b5-9601-f0fc26ef5eaf">

you see the price changes everytime a dropdown menu is selected, this is because when the user chooses a dropdown option, it'll pick up the values from whatever dropdown option they selected... then it'll check the other selected dropdown options and do a calculation and then update the price. That is the kind of information I'm waiting for.

**Comment by jillian-sun** [comment]
ohhh okay, so do you see still the updated code/txt file to see how the algorithm works?

**Comment by markendley** [comment]
well anything really
as long as I understand how the price is calculated

... a spreadsheet?
... maybe it can be explained in a simple email?

**Comment by jillian-sun** [comment]
will get some information for you - hold tight

**Comment by jillian-sun** [comment]
Hey mark, client said it's bit hard to explain so he provided logins for you to explore and play around:

Login email - info@pepperjune.co
Password - RspPj_2021
https://app.calconic.com/login

The calculator that is live is called "Pepper June Complete" and is accessible via the navigation bar on the left hand side
If mark clicks on any drop down or section of the calculator, he'll be able to see the breakdown in a pop up box
It's pretty logical once you're in there, so hopefully it all makes sense to him. If I can figure it out, no doubt he can. lol

**Comment by markendley** [comment]
Great, I undertstand how it works now!

**Comment by markendley** [comment]
Actually that form has got different fields to the form we have now. So the client is gonna help us fill the gaps.


"I would like a photobooth for..."
- How much for 3 hours
- 4?
- 5?

"I would like a Pepper June Car for..."
- How much is a Limo?
- How much is a van?

**Comment by jillian-sun** [comment]
I would just replicate what they have on their current form

**Comment by markendley** [comment]
ok finally
done :)
