### ISSUE TITLE
Pricing Collection Calculator – Amend line weights in the deposit/grand total area as per Figma design

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#42]
<img width="786" alt="Screenshot 2023-06-22 at 8 01 01 pm" src="https://github.com/markendley/pprjne/assets/137390062/37014b41-6b2a-4a8b-8236-b113b5ab06ff">

**Comment by markendley** [comment]
So they're gonna send us a script (an iframe) instead?

**Comment by jillian-sun** [comment]
Line weights still not amended

**Comment by markendley** [comment]
so we're still with the calculator I've built, ok, lines updated.
