### ISSUE TITLE
Blog Homepage – First column blog posts images are too cropped in - should fill image box at 100%

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#44]
<img width="505" alt="Screenshot 2023-06-22 at 8 07 47 pm" src="https://github.com/markendley/pprjne/assets/137390062/2822375d-dadf-455d-8968-283bb0c1c698">

**Comment by markendley** [comment]
fixed

**Comment by jillian-sun** [comment]
Can we fix the image height as per the figma design? (so we don't get variable heights in the images)

**Comment by markendley** [comment]
ok, how about now?

**Comment by jillian-sun** [comment]
perfection again, ty
