### ISSUE TITLE
Blog Homepage – Can the 2nd + 3rd column line extend to the bottom even when there are no posts?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#45]
<img width="902" alt="Screenshot 2023-06-22 at 8 09 38 pm" src="https://github.com/markendley/pprjne/assets/137390062/3cf73e7c-c1a0-4cdc-9ecc-aa6156a62405">

**Comment by markendley** [comment]
this page?

The line already extends down?

http://demoplatform.net/pepperjune/blog/

**Comment by markendley** [comment]
oh, I see what you mean now.

Done

**Comment by jillian-sun** [comment]
Thanks, but lines run across the homepage now 
<img width="1156" alt="Screenshot 2023-07-07 at 12 17 38 am" src="https://github.com/markendley/pprjne/assets/137390062/874b3a3a-87d8-483c-a674-66cebbb53051">

**Comment by markendley** [comment]
whoops fixed
