### ISSUE TITLE
Blog Homepage – Where is the field for excerpt text?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#46]
<img width="757" alt="Screenshot 2023-06-22 at 8 11 18 pm" src="https://github.com/markendley/pprjne/assets/137390062/5f9851cc-9297-4c3a-b3d3-ea8519a823dc">

**Comment by markendley** [comment]
At the bottom

<img width="533" alt="Screenshot 2023-07-06 at 6 44 13 pm" src="https://github.com/markendley/pprjne/assets/6570606/b3236ea1-8ad6-4fd5-8de6-e8775c2fe304">

**Comment by jillian-sun** [comment]
it doesn't show up for me? :( 

<img width="892" alt="Screenshot 2023-07-06 at 7 29 41 pm" src="https://github.com/markendley/pprjne/assets/137390062/2ddebe35-961e-4890-b163-7d994673d3f9">

**Comment by markendley** [comment]
On the top right hand corner, open screen options.

<img width="1516" alt="Screenshot 2023-07-06 at 9 45 51 pm" src="https://github.com/markendley/pprjne/assets/6570606/818be3fb-aea0-409b-ae5f-8f4dfa778f86">


Is Excerpt checked?
