### ISSUE TITLE
Home – category & location filter letter spacing incorrect + when you click on drop down, options disappear. currently it does not reflect Figma design.

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#47]
Incorrect:
<img width="454" alt="Screenshot 2023-06-22 at 8 12 18 pm" src="https://github.com/markendley/pprjne/assets/137390062/464e257b-9c2b-49d2-a62a-706a6e136d68">

Correct:
<img width="722" alt="Screenshot 2023-06-22 at 8 12 23 pm" src="https://github.com/markendley/pprjne/assets/137390062/86f82809-86a3-42b6-a017-9b3a092665ea">

**Comment by markendley** [comment]
I fixed the letter spacing, but I need more clarity on "options dissapear" could you elabourate please

**Comment by jillian-sun** [comment]
like when i cllck the drop down arrow, the filter options don't stay. they go away?

**Comment by markendley** [comment]
1. You click on the dropdown arrow
2. the dropdown menu opens
3. but then closes automatically?

**Comment by jillian-sun** [comment]
do you see for the right filter? Left filter also is placed on top when it should be bottom + letter spacing for the filter options is incorrect as well
https://github.com/markendley/pprjne/assets/137390062/2d53f94b-e081-426b-87e8-2dc0cce31582

Can we please amend the hover state styles to this: 

<img width="960" alt="Screenshot 2023-07-07 at 6 08 30 pm" src="https://github.com/markendley/pprjne/assets/137390062/8a8b1747-6388-44ef-9a0c-1261cf7d6983">

**Comment by jillian-sun** [comment]
Sorry we'll also just have to add an 'all' filter in there too for both category + location so users can revert back to viewing all posts and when they select, it will just go back to it's default state where the title is category or location. does this make sense?
<img width="269" alt="Screenshot 2023-07-07 at 6 33 08 pm" src="https://github.com/markendley/pprjne/assets/137390062/f00d584b-d233-4010-ae9d-5d903969ac10">

**Comment by markendley** [comment]
https://github.com/markendley/pprjne/assets/137390062/2d53f94b-e081-426b-87e8-2dc0cce31582

Oh I don't get that
You gotta tell me what browser your using
https://www.whatsmybrowser.org/

**Comment by jillian-sun** [comment]
google chrome @markendley 
<img width="786" alt="Screenshot 2023-07-10 at 12 18 44 am" src="https://github.com/markendley/pprjne/assets/137390062/c5889b21-83c8-44fd-ad09-873a4c144dcd">
<img width="818" alt="Screenshot 2023-07-10 at 12 18 52 am" src="https://github.com/markendley/pprjne/assets/137390062/706b8cd4-768f-4175-8156-5350fa2911c2">

**Comment by markendley** [comment]
thanks

All fixed

**Comment by jillian-sun** [comment]
hey mark, sorry but i cleared my cache and idk why but the filters are still jumping off when i click on the dropdrowns. the letter spacing & padding in the dropdowns + hover states still don't look like they've been fixed.

**Comment by markendley** [comment]
Ok, the reason why the filters are dropping up is because you're probably at the bottom of the window?

<img width="1466" alt="Screenshot 2023-07-13 at 8 50 02 pm" src="https://github.com/markendley/pprjne/assets/6570606/e92da698-1c39-4060-86c8-29efe73232c2">

But if you scroll up and then open them, they'll appear below like this
<img width="1450" alt="Screenshot 2023-07-13 at 8 50 09 pm" src="https://github.com/markendley/pprjne/assets/6570606/6291c5c1-999e-4ee6-8d44-5f00a5aa2fd3">

You see the if you're at the botton, it makes sense for the dropdown to appear above then below and get cropped off.

Hows the letter spacing and padding now?

**Comment by markendley** [comment]
I'm actually using a plugin to generate this dropdown (these dropdowns are really quite complicated).

**Comment by jillian-sun** [comment]
hey mark, so my issue is that when i click the dropdown, the filters don't actually stay on the screen. They disappear straight away after i click and it's still happening right now (refer to the video i sent a few threads ago).  

My other issues:

- the letter spacing for the filter options are still too tight can we please match the default state?
-  the hover states are different to my design, can we get rid of the black bar on hover and just reduce the opacity on the rest of the options that aren't hovered on? 
- Refer to my figma file for padding around the text as it's currently looking a little tight also, thanks!

<img width="274" alt="Screenshot 2023-07-13 at 9 56 17 pm" src="https://github.com/markendley/pprjne/assets/137390062/ea3a76c4-5dca-4adf-a1bd-e58b72041f32">

**Comment by markendley** [comment]
(ok, working on this)

**Comment by markendley** [comment]
oh of course, sorry, you're talking about the insdie the dropdown, ok...
this is what you're supposed to see....
<img width="477" alt="Screenshot 2023-07-14 at 5 42 25 am" src="https://github.com/markendley/pprjne/assets/6570606/cc30676c-9bd9-44d6-8b12-3060273c4ef1">

(working on the dissapearing)

**Comment by markendley** [comment]
Damn, I can't replicate 

> Screen.Recording.2023-07-07.at.6.03.07.pm.mov 
> Oh I don't get that You gotta tell me what browser your using https://www.whatsmybrowser.org/

Damn, I still can't replicate this

I also tested Edge, Firefox, Safari. 

The dropdowns even work on IE11 (even though nothing else does).

.... Is it just your computer?
The next step would be for me to jump your on your computer and do a play (ever used Teamviewer before?)

**Comment by jillian-sun** [comment]
actually it all seems to be working great now - thank you so much mark!!

**Comment by jillian-sun** [comment]
Can we just make sure the filter options always drop below? it just ensures there's no weird gap above. thanks 
<img width="341" alt="Screenshot 2023-07-15 at 6 33 26 pm" src="https://github.com/markendley/pprjne/assets/137390062/e26c73d0-6fcd-453f-97d6-ad71f5160434">

**Comment by markendley** [comment]
OK, I found a way to override this, and now I can force that dropdown to appear below no matter what. It works!

Awaiting confirmation

**Comment by jillian-sun** [comment]
perfection, thanks mark

**Comment by jillian-sun** [comment]
hey mark, sorry i just noticed that when you click on the filters from the top (no scrolling) - the options jump off and don't stay on the screen again. They disappear straight away after i click on it. and when i try to scroll after, it happens again after clicking. But when i refresh and scroll + click on filters, it works fine. can we please ensure this doesn't happen if someone tries to click on the filters from the top?

**Comment by jillian-sun** [comment]
- also now when i test the location filters, they dont work. they just show all blog posts, no matter which location i select. 
- can we please also hide the 'category' + 'location' + 'jump to' options as they do the same thing if you click on 'All'. So when user selects 'All', it should just display the default state title (i.e. category/location/jump to) - let me know if this doesn't make sense to you
<img width="491" alt="Screenshot 2023-07-18 at 10 00 34 am" src="https://github.com/markendley/pprjne/assets/137390062/1f8a4777-b5ff-43d5-854e-5caa97faa48e">

<img width="887" alt="Screenshot 2023-07-18 at 9 59 15 am" src="https://github.com/markendley/pprjne/assets/137390062/38aeef72-1ae4-4309-96e5-62dcac3e7c56">

**Comment by markendley** [comment]
OK I fixed the dropdown menu items

Sorry I couldn't replicate the other issues on my end... you sure?
I'll proceed with the launch now!

**Comment by jillian-sun** [comment]
hey mark! just looking at the dropdowns. i think i prefer it when it said 'category' + 'location'. can we please change back the wording? sorry!! once that's done, im good for launch!

**Comment by markendley** [comment]
easy done
