### ISSUE TITLE
Blog Homepage – can we please add in the choice of what article gets featured at the top in the mustard BG?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#48]
<img width="1512" alt="Screenshot 2023-06-22 at 8 13 39 pm" src="https://github.com/markendley/pprjne/assets/137390062/f0546f29-4b53-4a02-b530-03f496595b09">

**Comment by markendley** [comment]
Certainly

When you go to the Blog page, you'll see a new field called "Feature Article".

if you leave this field empty, then it'll just default to the latest post published.

**Comment by jillian-sun** [comment]
sorry is this what you mean? 
<img width="1623" alt="Screenshot 2023-07-07 at 1 22 19 pm" src="https://github.com/markendley/pprjne/assets/137390062/94d6e25c-c780-496b-9307-a8dd9c70cedb">

Also when the feature image of the featured post is portrait, can it just crop to the same landscape ratio as the 1st column blog post?

<img width="1602" alt="Screenshot 2023-07-07 at 1 19 03 pm" src="https://github.com/markendley/pprjne/assets/137390062/f7ef304b-bb70-4295-89ad-61b493c81685">

to this:
<img width="691" alt="Screenshot 2023-07-07 at 1 19 11 pm" src="https://github.com/markendley/pprjne/assets/137390062/25f5e334-d891-4f46-b9b4-7b25d0c41924">

**Comment by markendley** [comment]
oh it disspeared. I just put it back, can you see it now?

**Comment by markendley** [comment]
I'm running the images through the cropping process again, it'll take a few mintues.

**Comment by jillian-sun** [comment]
still coming up as portrait for me and i've cleared by cache.

**Comment by markendley** [comment]
The cropping process is complete now

see: http://demoplatform.net/pepperjune/blog/

**Comment by jillian-sun** [comment]
perfection! and just back on that note about where to find the featured post, is it here?:
<img width="1623" alt="Screenshot 2023-07-07 at 1 22 19 pm" src="https://github.com/markendley/pprjne/assets/137390062/d4dabeff-b5e4-48e8-8add-d8aa022542c5">

**Comment by markendley** [comment]
Hmm it dropped off again.

Can you see it now?

<img width="1862" alt="Screenshot 2023-07-07 at 4 55 07 pm" src="https://github.com/markendley/pprjne/assets/6570606/cbde8b51-dce1-4956-919e-db41f7a8588a">
