### ISSUE TITLE
Blog Article – Can we have the option to embed youtube/vimeo videos in a blog post?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#49]

**Comment by markendley** [comment]
Ready

see it in action....
http://demoplatform.net/pepperjune/sinead-thomas-intimate-and-traditional-chiswick-restaurant-wedding-clone-2/

**Comment by jillian-sun** [comment]
thank you! I noticed the padding between banner and blog post content is too tight, can we increase it to 64px?
<img width="1512" alt="Screenshot 2023-07-06 at 10 35 50 pm" src="https://github.com/markendley/pprjne/assets/137390062/638a26cb-c56e-4aa1-be26-9a207e456066">

**Comment by markendley** [comment]
fixed
