### ISSUE TITLE
Dropdown menu – Where do I change the images for each service category?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#5]
<img width="499" alt="Screenshot 2023-06-22 at 6 40 00 pm" src="https://github.com/markendley/pprjne/assets/137390062/f1610fa6-29ed-4dd6-b275-af5c245ddbf0">

**Comment by markendley** [comment]
1. Go to **Appearance**
2. **Menus**
3. **Top left**
<img width="1197" alt="Screenshot 2023-07-06 at 6 28 09 pm" src="https://github.com/markendley/pprjne/assets/6570606/4c827172-b201-4ea2-a9fa-bb8a0e1ec426">
