### ISSUE TITLE
Blog Article – Can we please embed links for the vendors that open on a new tab?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#50]
<img width="978" alt="Screenshot 2023-06-22 at 8 15 17 pm" src="https://github.com/markendley/pprjne/assets/137390062/e0849b66-3a21-40af-bc8b-d551b29cc331">

**Comment by markendley** [comment]
done, created a new field called URL

see it in action with this one
http://demoplatform.net/pepperjune/sinead-thomas-intimate-and-traditional-chiswick-restaurant-wedding-clone-2/

**Comment by jillian-sun** [comment]
Amazing, can we please make links open in a new tab and not current tab?

**Comment by markendley** [comment]
done
