### ISSUE TITLE
Blog Article – If featured image is portrait, can it please be cropped landscape to the dimensions in Figma design? (centre focus point)

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#51]
<img width="1512" alt="Screenshot 2023-06-22 at 8 16 50 pm" src="https://github.com/markendley/pprjne/assets/137390062/34c10ddf-90a5-4710-9d7a-146237daa345">

**Comment by jillian-sun** [comment]
I just uploaded a landscape image and it also crops - it should fill width

<img width="1918" alt="Screenshot 2023-07-06 at 7 26 10 pm" src="https://github.com/markendley/pprjne/assets/137390062/d3c6568c-9001-45b9-8fa1-27ad4e938cec">

**Comment by markendley** [comment]
sorry, the code i wrote for this dropped off

fixed
