### ISSUE TITLE
Blog Article – spacing between date, category, location titles are inconsistent

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#52]
Incorrect: 
<img width="304" alt="Screenshot 2023-06-22 at 8 17 48 pm" src="https://github.com/markendley/pprjne/assets/137390062/ab3169c7-f8a1-434e-b0fa-e239432f0803">

Correct:
<img width="528" alt="Screenshot 2023-06-22 at 8 17 57 pm" src="https://github.com/markendley/pprjne/assets/137390062/2cdecac4-45ae-4942-b7fe-8df2daa10866">

**Comment by markendley** [comment]
fixed
