### ISSUE TITLE
Blog Article – If landscape + portrait images are uploaded side by side, can they please be displayed at the same height?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#53]
<img width="929" alt="Screenshot 2023-06-22 at 8 16 29 pm" src="https://github.com/markendley/pprjne/assets/137390062/4cedaa29-c25f-4456-a55a-de8b726fdbd8">

**Comment by markendley** [comment]
fixed

**Comment by markendley** [comment]
please upload portrait images into this field, otherwise landscape images might scale up too much and you might not like how it crops.

**Comment by jillian-sun** [comment]
can we make the height adjustable so that landscape images don't get cropped? something more along the lines of this:

<img width="707" alt="Screenshot 2023-07-06 at 10 15 40 pm" src="https://github.com/markendley/pprjne/assets/137390062/4863fbc9-3830-44a8-9d9b-6c918d45a9bf">

**Comment by markendley** [comment]
I could add another field, so you can choose the ratios...

50:50
70:30
30:70

Would that work?
It'll be an extra $150 though

**Comment by jillian-sun** [comment]
I think if we could just make it so that if you upload a landscape image with a portrait image, it will just automatically display them both at the same height without cropping any image. I would prefer not to add in more ratio options incase they upload and choose the wrong ratio and it displays weirdly. this will just make it easier for the user. lmk if this is possible.

**Comment by markendley** [comment]
Easier for the user, but not easy for me.


> automatically display them both at the same height without cropping any image

No sorry, I don't think it's possible to do it without cropping

**Comment by jillian-sun** [comment]
if you add 30:70 and 70:30, will those images still display at the same height then?

**Comment by markendley** [comment]
Yes

Remember, what I'm doing is creating image **containers**, and then the **image just fills up** those containers.

**Comment by jillian-sun** [comment]
Ok let's go ahead with adding those additional rations for extra $150. thanks mark

**Comment by markendley** [comment]
ready, I did it to this draft
http://demoplatform.net/pepperjune/?p=1586&preview=true

What do you think....
http://demoplatform.net/pepperjune/?p=1586&preview=true

we can add in 60:40 and 40:60 if you want.

**Comment by jillian-sun** [comment]
looks great! is what you just showed me 60:40 or 70:30?

**Comment by markendley** [comment]
70:30 is what you're seeing right now

**Comment by jillian-sun** [comment]
will it take too long to see what 60:40 / 40:60 looks like? I just want to see which looks better

**Comment by markendley** [comment]
nope, just did it

you'll now see 60:40 and 40:60 in the options, see what happens when you select them

**Comment by jillian-sun** [comment]
lets stick to 30:70 / 70:30. thanks for showing me the options.

**Comment by markendley** [comment]
your welcome
done
