### ISSUE TITLE
Jump to – letter spacing incorrect + when you click on drop down, options disappear. currently it does not reflect Figma design.

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#57]
incorrect:
<img width="257" alt="Screenshot 2023-06-22 at 8 22 10 pm" src="https://github.com/markendley/pprjne/assets/137390062/3999fd4c-f20b-4076-9826-0096e8d9d0ee">

Correct:
<img width="192" alt="Screenshot 2023-06-22 at 8 22 24 pm" src="https://github.com/markendley/pprjne/assets/137390062/b8018ee4-df04-4ad5-9215-cdc2bb3c5b28">

**Comment by markendley** [comment]
I fixed the letter spacing, but I need more clarity on "options dissapear" could you elabourate please

**Comment by jillian-sun** [comment]
see #47

**Comment by jillian-sun** [comment]
Hey mark, 

can we make sure the filters are always displayed
