### ISSUE TITLE
Blog Post – bullet/number lists don't appear 

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#66]
<img width="1192" alt="Screenshot 2023-07-09 at 5 11 25 pm" src="https://github.com/markendley/pprjne/assets/137390062/a9074565-d865-4147-8722-f0026ee018f7">

<img width="822" alt="Screenshot 2023-07-09 at 5 10 36 pm" src="https://github.com/markendley/pprjne/assets/137390062/a8cf20c6-8e02-4b69-9ea4-94e7b8fbff73">

**Comment by markendley** [comment]
ready
