### ISSUE TITLE
About page - flashing on the landing team image 

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#67]
I think this is because it's designed as a slideshow and the flashing is acting as a transition for the next image, but if there's only 1 image, can we make sure there is no flashing of the image?

<img width="961" alt="Screenshot 2023-07-10 at 4 12 03 pm" src="https://github.com/markendley/pprjne/assets/137390062/4f168185-1fd0-4aee-a839-f2fcaf16bed1">

**Comment by markendley** [comment]
fixed
