### ISSUE TITLE
Blog Post - some photos don't crop properly with the 30:70/70:30 ratio?

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#68]
<img width="888" alt="Screenshot 2023-07-10 at 10 26 50 pm" src="https://github.com/markendley/pprjne/assets/137390062/e51c7e68-10e2-4713-be9b-89ada1ed574b">
<img width="839" alt="Screenshot 2023-07-10 at 10 27 54 pm" src="https://github.com/markendley/pprjne/assets/137390062/eb4476f7-513f-47e8-a58e-7de458457f2e">

can we also please make the height of this ratio be 356px? it's a little too short atm. thanks

**Comment by markendley** [comment]
This would be http://demoplatform.net/pepperjune/natalie-joshs-emotional-and-cheerful-novella-on-the-park-wedding/ right?

You have to put a **portrait** image in a **portrait** container.


The height is now higher.
