### ISSUE TITLE
Audio Guest Book - how it works section has disappeared

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#69]
<img width="1449" alt="Screenshot 2023-07-10 at 10 54 07 pm" src="https://github.com/markendley/pprjne/assets/137390062/9dad90e8-b713-4b5a-ad8c-371b1818faef">

**Comment by markendley** [comment]
The sliders?

maybe you didn't see it because  I was working on that page?

Can you see it now?

<img width="1891" alt="Screenshot 2023-07-11 at 5 23 21 pm" src="https://github.com/markendley/pprjne/assets/6570606/540fc08d-1859-4e92-830c-5338f67d46a1">

**Comment by jillian-sun** [comment]
Cleared by cache and it's still not there on google chrome. it shows up on safari though.

**Comment by markendley** [comment]
fixed
