### ISSUE TITLE
Photography Page – image banner overlaps with text - doesn't reflect figma design 

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#70]
<img width="1510" alt="Screenshot 2023-07-15 at 6 02 16 pm" src="https://github.com/markendley/pprjne/assets/137390062/f5f334e6-590b-49a1-ae13-546f3e8b938c">

should be this:
<img width="918" alt="Screenshot 2023-07-15 at 6 04 00 pm" src="https://github.com/markendley/pprjne/assets/137390062/4edc9893-2d74-4657-b752-03289092b0b2">

**Comment by markendley** [comment]
fixed
