### ISSUE TITLE
Blog Page – when user changes a filter, nothing displays until you scroll

### ISSUE THREAD

**Issue by jillian-sun** [markendley/pprjne#71]
from client: We noticed when you change a filter on the blog page, there seemed to be a bug where nothing on the page shows until you scroll. Can we please ensure the blog articles are displayed straight away? 

<img width="1508" alt="Screenshot 2023-07-15 at 6 38 03 pm" src="https://github.com/markendley/pprjne/assets/137390062/9f6b7b59-ae26-42fc-a2c2-cef95c526a1a">

**Comment by markendley** [comment]
fixed
